### ISSUE TITLE
False Positive: NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE when code throws NullReferenceException explicitly (as Objects.requireNonNull does)

### ISSUE THREAD

**Issue by Zastai** [spotbugs/spotbugs#1175]
Spotbugs Version: `com.github.spotbugs:spotbugs-maven-plugin:4.0.0`, with `com.github.spotbugs:spotbugs-annotations:4.0.3`

Method:
```java
@NonNull
public static Foo foo() {
  final Foo foo = Foo.something(); // method not annotated, so could return null
  return Objects.requireNonNull(foo, "Oops.");
}
```
This seems perfectly sensible, but results in `Possible null pointer dereference in xxx.foo() due to return value of called method - NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE` being reported for the `return`.

Inlining `requireNonNull()`:
```java
@NonNull
public static Foo foo() {
  final Foo foo = Foo.something(); // method not annotated, so could return null
  if (foo == null)
    throw new NullPointerException("Oops.");
  return foo;
}
```
results in `Known null. NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE`.

Throwing any other exception (e.g. `RuntimeException`) makes the error report go away.

**Comment by gloNelson** [comment]
@Zastai It seems that the issue had been fixed in the latest version when I tried to reproduce it. Could you retry and give a reply?

**Comment by Zastai** [comment]
Just tried it with spotbugs-maven-plugin 4.1.3 and could not reproduce either case, so this indeed seems fixed.

**Comment by dee-kryvenko** [comment]
This still reproducible for me using the following code:

```java
        try (SCMFileSystem fs = SCMFileSystem.of(job, scm)) {
            if (fs == null) {
                throw new NullPointerException("Unable to create FS for SCM");
            }

            ...
        }
```

It doesn't seem to understand `throw` here, if I replace it with a simple `return` - it goes away.
