### ISSUE TITLE
false positive RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE on try-with-resources

### ISSUE THREAD

**Issue by jhonnen** [spotbugs/spotbugs#259]
FindBugs (eclipse plugin v3.0.1) reports a redundant null check on the closing brace of the following try-with-resources statement:
  
    public void falsePositive() {
      try (X x = new X(); X y = new X()) {
        throw new IllegalStateException();
      } // Redundant nullcheck of x, which is known to be non-null in test.Bug1169.falsePositive()
    }
  
    private static class X implements AutoCloseable {
      @Override
      public void close() {
      }
    }

The finding seems to be reported when more than one AutoClosable is used and the try block ends with a thrown exception.

**Comment by KengoTODA** [comment]
Please have a try with SpotBugs, it should be already solved by SpotBugs.

**Comment by Gubbel** [comment]
@KengoTODA I've reproduced the same false positive with the eclipse spotbugs plugin 3.1.0.20170610-1497060633070:

```
Bug: Redundant nullcheck of x, which is known to be non-null in test.Issue259.falsePositive()

This method contains a redundant check of a known non-null value against the constant null.

Rank: Of Concern (20), confidence: Low
Pattern: RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE 
Type: RCN, Category: STYLE (Dodgy code)
```

Note that the finding is filtered with initial settings since it's rank 20 and low confidence.

**Comment by aburmeis** [comment]
still occuring using 3.1.7:
```
        try (Connection con = dataSource.getConnection()) {
            DatabaseMetaData meta = con.getMetaData();
            return ...
        } catch (SQLException e) {
            return false;
        }
```

Nullcheck of con at line ... of value previously dereferenced in ...[line <meta =>]Redundant null check at ...:[line <catch>] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE

**Comment by izrobin** [comment]
Can confirm this is still an issue. Ping pong

**Comment by pbludov** [comment]
This bug affects checkstyle openjdk 11 build:
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/20856366/job/7h2g68dviuollcuc
```
[ERROR] Redundant nullcheck of stream, which is known to be non-null
in com.puppycrawl.tools.checkstyle.Main.loadProperties(File)
[com.puppycrawl.tools.checkstyle.Main, com.puppycrawl.tools.checkstyle.Main]
Redundant null check at Main.java:[line 411]Another occurrence at Main.java:[line 413]
RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
```
The lines 411-413 of [main.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L411) are
```
    try (InputStream stream = Files.newInputStream(file.toPath())) {
        properties.load(stream);
    }
```

**Comment by bazi** [comment]
Having the same false positive with v3.1.10. Using maven plugin.

Let me elaborate a little about the cause of this issue.
`Try-with-resources` statements are translated to simple `try` statements with local variable definitions. Translation can be found in [Java Language Specification, section 14.20.3.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3.1).

There we can clearly see how resources are declared as local variables before try statement and thereafter closed in finally block first being checked for nullity. And here we get redundant null check warning because that variable was used in our try block.

I don't know the code base of Spotbugs and quick overview didn't revealed details of its working, so I didn't try to make a fix. I hope that will be fixed soon, or if not, I may spend some time on my spare time.

**Comment by bbzg** [comment]
Happened to me too, SpotBugs 3.1.8, try-with-resources, Java 11

**Comment by Flugtiger** [comment]
+1 Eclipse Plugin 3.1.10r201812180244

**Comment by KengoTODA** [comment]
#284 has proved that the reported problem has been solved. So I think yours is different and new problem. Please consider to make an unit test to reproduce, and submit PR to merge it to release-3.1 branch. :bow:

**Comment by stevenschlansker** [comment]
Can confirm this still affects Spotbugs 3.1.10, hopefully #259 will show that not all cases are fixed yet.

**Comment by mmoehring** [comment]
Is this related to https://github.com/spotbugs/spotbugs/issues/756?

**Comment by romani** [comment]
still problem on 3.1.12.2

**Comment by astappiev** [comment]
Still persists on 4.0.0

**Comment by Zlika** [comment]
Hi @KengoTODA .
I tested Spotbugs 4.1.3 with Java 11 on my project. This new version resolved all the 7 RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE false positives I had (#878). However, it did not solve any of the 12 RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE false positives I have, all located on a line of a "try-with-resource" statement.

**Comment by Zlika** [comment]
I've made a very small sample project to reproduce #259 (and also #811) with Spotbugs 4.1.3.

**Comment by Zlika** [comment]
The problem seems to be fixed by upgrading the spotbugs-maven-plugin to version 4.1.3. Previously I used spotbugs-maven-plugin 4.0.4 with a forced dependency to spotbugs 4.1.3 (as in https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html). This seems to have some side effects.

**Comment by 95Kevid** [comment]
We still have the issue with 4.2.2 :-(. (false positive inside try with resources block)
