### ISSUE TITLE
US_USELESS_SUPPRESSION_ON_* is too opinionated

### ISSUE THREAD

**Issue by asheldon** [spotbugs/spotbugs#3396]
The documentation reads:
> Leaving them may result in accidental warnings suppression. The annotation was probably added to suppress a warning raised by SpotBugs, but now SpotBugs does not report the bug anymore. Either the bug was solved or SpotBugs was updated, and the bug is no longer raised by that code.

One scenario ignored by this is code generators, like Immutables, [Lombok](https://github.com/projectlombok/lombok/issues/3867), or any other scenario where the generator adds @SuppressFBWarnings to generated code to avoid SpotBugs warnings. In the view of a code generator's users, there's no value in findings in the generated code. However, a code generator author cannot know which defects SpotBugs may find in their generated code now, in the future, or with plugins. It makes sense for them to defensively suppress all warnings, even if they have none. However, if they have no warnings to suppress, they now have a US_USELESS_ warning.

This leads to my second scenario, when a bug is suppressed both by findbugs-exclude.xml and also by an annotation. In organizations of almost any size, it's not uncommon to have shared findbugs-exclude.xml files that are used across multiple Java projects. When the organization deems a particular detector should be disabled by default, they update their findbugs-exclude.xml and the "useless" annotations become a harmless form of historical documentation. No one needs to "fix" them because there's nothing to fix. 

Removing these annotations is work without benefit and makes it harder to adopt new versions of SpotBugs. Annotations aren't "useless" just because they're not currently suppressing something. The problem with "useless" annotations is not that they're useless, but that they may be documenting the existence and suppression of a bug that does not exist, and in generated code, not even that.

Between these two scenarios, it has become very difficult to avoid useless triggering of US_USELESS_SUPPRESSION_ON_ without shutting them off entirely. Even this is unusually difficult for this new detector as it cannot be disabled by modifying findbugs.xml and rebuilding the jar.

**Comment by ThrawnCA** [comment]
Agreed. I can see the merit in saying, "Once you've fixed a bug, you don't need to hide it anymore in case it crops back up." But sometimes the reason for a suppression is because the nature of the code is that you simply don't care if a detector would find problems with it.

**Comment by gtoison** [comment]
PR #3409 should help with scenario 1 by silencing `US_USELESS_SUPPRESSION_ON_*` when the code is annotated with `*.Generated`.

I'm not sure what to do with scenario 2: if the bugs are ignored with a `findbugs-exclude.xml` filter and also by annotations, but now these annotations are unnecessary how would SpotBugs know that they are "historical documentation"?

**Comment by asheldon** [comment]
I think suppression annotations should only be considered useless when they would be useless even without a `findbugs-exclude.xml` file. This makes the output of SpotBugs more stable.

This approach makes it so the code being evaluated, and its documented suppressions, create the same `US_USELESS_SUPPRESSION_*` discoveries regardless of `findbugs-exclude.xml`. People shouldn't have to think about whether the annotations are processed first or the `findbugs-exclude.xml` rules are processed first. 

The right behavior when suppressing bugs reported by SpotBugs plugins is more difficult because you can't really ascertain if an annotation is useless or not if you can't evaluate it, which is bad for stability.

**Comment by matthall-TM** [comment]
Hi, we are having similar issues. After upgrading to spotbugs 4.9.3 a lot of our suppressions are being reported as USELESS but removing them brings back the original complaints. for instance

@Builder
@SuppressFBWarnings({"EI_EXPOSE_REP", "EI_EXPOSE_REP2"})
public record Test(String name, List<String> urls,
    boolean notFound) {}

now reports the suppression is USELESS, yet removing the suppression (or just removing one) brings back the original complaint.

This is happening at the class, method, and parameter level.

**Comment by gtoison** [comment]
The issue with records seems to be #3471 which was fixed (the upcoming version of Spotbugs will have the fix)

**Comment by klopfdreh** [comment]
Updated to `spotbugs-maven-plugin` with version `4.9.6.0` which uses `spotbugs` with version `4.9.6` and still get those messages of `US_USELESS_SUPPRESSION_ON_CLASS` - when I remove the annotations I get the previous spotbugs issues as mentioned in the description.

Edit: I double checked it and it seems that the spotbugs issues are valid. The issue raised where not the same as before. I removed the `SuppressFBWarnings` annotation and added only those suppressions which where mentioned in a second build. It worked perfectly fine in this case.

@asheldon can you confirm that it is working for you as well?
