### ISSUE TITLE
xsd out of date in 3.1.0

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs#492]
```
The following errors occurred during analysis:
  Unable to read filter: /pipeline/source/config/spotbugs/exclude.xml : Failing reading /pipeline/source/config/spotbugs/exclude.xml Nested exception: Sax error while parsing /pipeline/source/config/spotbugs/exclude.xml Nested exception: Invalid top-level element (expected BugCollection, saw FindBugsFilter)
    org.dom4j.DocumentException: Failing reading /pipeline/source/config/spotbugs/exclude.xml Nested exception: Sax error while parsing /pipeline/source/config/spotbugs/exclude.xml Nested exception: Invalid top-level element (expected BugCollection, saw FindBugsFilter)
      At edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:276)
      At edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:257)
      At edu.umd.cs.findbugs.ExcludingHashesBugReporter.addToExcludedInstanceHashes(ExcludingHashesBugReporter.java:57)
      At edu.umd.cs.findbugs.ExcludingHashesBugReporter.<init>(ExcludingHashesBugReporter.java:44)
      At edu.umd.cs.findbugs.FindBugs.configureBaselineFilter(FindBugs.java:519)
      At edu.umd.cs.findbugs.FindBugs2.excludeBaselineBugs(FindBugs2.java:376)
      At edu.umd.cs.findbugs.FindBugs2.configureFilters(FindBugs2.java:483)
      At edu.umd.cs.findbugs.FindBugs2.setUserPreferences(FindBugs2.java:472)
      At edu.umd.cs.findbugs.TextUICommandLine.configureEngine(TextUICommandLine.java:670)
      At edu.umd.cs.findbugs.FindBugs.processCommandLine(FindBugs.java:365)
      At com.github.spotbugs.internal.spotbugs.SpotBugsExecuter.runSpotbugs(SpotBugsExecuter.java:22)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
      At org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:83)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
```
my exclude xml
```
<?xml version="1.0" encoding="UTF-8"?>
<FindBugsFilter
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://github.com/spotbugs/filter/3.0.0"
  xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
</FindBugsFilter>
```

if the top level element has changed I would suggest also changing the version on the filter

docs are also out of date http://spotbugs.readthedocs.io/en/stable/filter.html

**Comment by KengoTODA** [comment]
Do you know which change caused this error? I cannot find the change in `findbugsfilter.xsd`, it has following two changes only:

* https://github.com/spotbugs/spotbugs/commit/672647a15cf22d1426f5ff2b92979a57907242d3#diff-7ea217c9c4df7e7e4b8a6eca60ed6f1f
* https://github.com/spotbugs/spotbugs/commit/6a5f6e7b98c20b8cda587ef67d3161d228362057#diff-808d5dafffc1ba3105dc58d934516d61

**Comment by xenoterracide** [comment]
that's actually the problem, the xsd didn't change, but the code is now expecting the root element to be `BugsCollection` I'm not sure where that changed.

**Comment by xenoterracide** [comment]
https://bitbucket.org/xenworks/util/commits/faec1b953b6a4607dbc8ee95669e7a8003408b24 this commit `./gradlew spotbugsMain` can reproduce.

**Comment by xenoterracide** [comment]
bump

**Comment by xenoterracide** [comment]
wow... still no fix?

**Comment by xenoterracide** [comment]
actually this does appear to have been fixed as FindBugsFilter is now allowed again when parsing, which is in accordance with the XSD.

**Comment by kungfoo** [comment]
This XML still fails to parse with spotbugs gradle plugin 2.0.0:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FindBugsFilter
	xmlns="https://github.com/spotbugs/filter/3.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.12/spotbugs/etc/findbugsfilter.xsd">
	<Match>
		<Method returns="io.reactivex.disposables.Disposable" name="subscribe"  />
		<Bug pattern="RV_RETURN_VALUE_IGNORED" />
	</Match>
</FindBugsFilter>
```

What gives?
